# Generated by Django 3.1.2 on 2020-11-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201116_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='code',
            field=models.IntegerField(),
        ),
    ]
