# Generated by Django 3.1.2 on 2020-11-16 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20201116_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='code',
            old_name='userka',
            new_name='user',
        ),
    ]
