# Generated by Django 3.1.2 on 2020-11-17 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20201117_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Code',
        ),
    ]
