# Generated by Django 3.1.2 on 2020-12-05 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201205_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='support',
            name='user',
        ),
    ]
