# Generated by Django 3.1.2 on 2020-12-05 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_support_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Support',
        ),
    ]
