# Generated by Django 3.1.2 on 2021-04-13 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_premka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premka',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 5, 13), verbose_name='дата окончани'),
        ),
    ]
