# Generated by Django 3.1.2 on 2021-04-13 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_auto_20210413_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premka',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 4, 13), verbose_name='дата покупки'),
        ),
    ]
