# Generated by Django 3.1.2 on 2021-04-24 02:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20210414_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premka',
            name='date_end',
            field=models.DateField(default=datetime.date(2021, 5, 24), verbose_name='дата окончани'),
        ),
        migrations.AlterField(
            model_name='premka',
            name='date_start',
            field=models.DateField(default=datetime.date(2021, 4, 24), verbose_name='дата покупки'),
        ),
    ]
