# Generated by Django 3.1.2 on 2021-04-24 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20210424_1217'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Профиль.', 'verbose_name_plural': 'Профили'},
        ),
    ]
