# Generated by Django 3.1.2 on 2021-04-24 10:33

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20210424_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to=users.models.Profile.get_image_path),
        ),
    ]
