# Generated by Django 3.1.2 on 2020-11-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('movie', models.URLField(verbose_name='Кино')),
                ('year', models.DateTimeField(verbose_name='Год выхода')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('author', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'кино',
                'verbose_name_plural': 'фильмы',
            },
        ),
    ]
