# Generated by Django 3.1.2 on 2020-11-12 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movies_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'сериал', 'verbose_name_plural': 'сериалы'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie',
            field=models.URLField(verbose_name='Сериал'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(default='', upload_to='serials/', verbose_name='изображение'),
        ),
    ]
