# Generated by Django 3.1.2 on 2020-11-12 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20201112_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='Serials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='Название')),
                ('movie', models.URLField(verbose_name='Сериал')),
                ('year', models.IntegerField(verbose_name='Дата выхода')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('author', models.CharField(max_length=100, verbose_name='Режиссер')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(default='', upload_to='serials/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'сериал',
                'verbose_name_plural': 'сериалы',
            },
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'кино', 'verbose_name_plural': 'фильмы'},
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie',
            field=models.URLField(verbose_name='Кино'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster',
            field=models.ImageField(default='', upload_to='films/', verbose_name='изображение'),
        ),
    ]
