# Generated by Django 3.1.2 on 2020-12-07 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_comments_movie'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterField(
            model_name='comments',
            name='user',
            field=models.CharField(max_length=70, verbose_name='Имя'),
        ),
    ]
