# Generated by Django 3.1.2 on 2020-12-07 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_remove_comments_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='movie',
        ),
    ]
