# Generated by Django 3.1.2 on 2020-12-07 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_auto_20201207_1812'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='serial',
        ),
    ]
