# Generated by Django 3.1.2 on 2020-12-08 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0016_remove_comments_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='ser',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='movies.serials'),
        ),
    ]
