# Generated by Django 3.1.2 on 2020-12-08 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0020_auto_20201208_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movies.movies'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='ser',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movies.serials'),
        ),
    ]
