# Generated by Django 3.1.2 on 2020-12-08 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0026_comments_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='ser',
            field=models.ForeignKey(default='cdasdasd', on_delete=django.db.models.deletion.CASCADE, to='movies.serials'),
        ),
    ]
