# Generated by Django 3.1.2 on 2020-12-08 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0030_comments_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='serial',
        ),
    ]
