# Generated by Django 3.1.2 on 2020-12-08 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0037_auto_20201208_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='textwerwe',
            field=models.CharField(default=None, max_length=90, verbose_name='rwer'),
        ),
    ]
