# Generated by Django 3.1.2 on 2020-12-08 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0038_comments_textwerwe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='textwerwe',
        ),
    ]
