# Generated by Django 3.1.2 on 2020-12-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0042_auto_20201209_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='serial',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='movies.serials'),
        ),
    ]
