# Generated by Django 3.1.2 on 2020-12-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0043_comments_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to='avatars-comm/'),
        ),
    ]
