# Generated by Django 3.1.2 on 2020-12-18 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0045_auto_20201218_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(default='', max_length=70, verbose_name='Имя'),
        ),
    ]
