# Generated by Django 3.1.2 on 2020-12-18 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0047_auto_20201218_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='user',
            field=models.CharField(max_length=70, verbose_name='user'),
        ),
    ]
