# Generated by Django 3.1.2 on 2020-12-24 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0051_likes_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewsCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
