# Generated by Django 3.1.2 on 2020-12-24 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0052_viewscounter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ViewsCounter',
        ),
    ]
